version: "3.8"
services:
    order-service:
        image: order-service:1.0.0
        container_name: order-service
        ports:
            - 8081:8080
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://root:rootpass@172.17.0.1:27017/admin
            - OTEL_TRACES_EXPORTER=otlp
            - OTEL_METRICS_EXPORTER=otlp
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://172.17.0.1:4317
            - OTEL_TRACES_SAMPLER=always_on
            - OTEL_IMR_EXPORT_INTERVAL=5000
            - OTEL_METRIC_EXPORT_INTERVAL=5000
            # - OTEL_RESOURCE_ATTRIBUTES=service.name=order-service,service.version=1.0.0